name: Deploy to Glitch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Glitch
        run: |
          curl -X POST "https://api.glitch.com/projects/strengthened-difficult-philosophy/import/git" \
          -d "authorization=YOUR_GLITCH_PROJECT_TOKEN"
